### ISSUE TITLE
Installation question.

### ISSUE THREAD

**Issue by kingdotIO** [GoldenDrakeStudios/golden-drake-linux#1]
What is GDS exactly? I know it's Arch based, gaming etc. but what's the motive and goal, overall and this is coming from the ArchLabs Forums who were discussing it today, why GDS & what is reason for creating this mysterious yet beautiful distro, instead of using Garuda for example. Serious questions, not sarcasm as I may be replacing my main systems OS yet again depending what it offers.

**Comment by theDrake** [comment]
Thank you for asking! To be honest, GDL started primarily just to serve as my own custom Arch installer and as an opportunity to deepen my knowledge of Linux, bash scripting, etc. Naturally, I did—and still do—hope that it might be useful to a few other gamers/devs as well, but I certainly don't expect it to become "super popular" since its focus is quite narrow, it's built largely around my own preferences, and it isn't as flexible as many other installers (e.g., only four major DEs are currently offered, no WM options), such as ArchLabs (a project I greatly admire, by the way, and, truth be told, at one point in my development of GDL I decided I wish I'd forked ArchLabs instead of Anarchy).

So, why should a gamer or game dev consider GDL?

1. It provides menus during installation for a ton of FOSS games, gaming-related software, development-related software, video recording/streaming/editing software, etc., inc. some carefully-selected AUR packages.
2. Helpful configurations are applied according to detected hardware (e.g., if an NVIDIA card and another GPU are detected, GameMode will be configured so it also activates `prime-run` to ensure the NVIDIA card does all the heavy lifting when using `gamemoderun`; if Timeshift is selected for a Btrfs system, Timeshift will be configured to begin automatically creating system snapshots periodically and before each upgrade; etc.).
3. It's essentially "pure Arch" in the sense that it only uses official Arch repos and the AUR (unlike Garuda, EndeavourOS, Manjaro, etc.) and yet, for all but the most experienced Arch users, it's quicker, more convenient, and less intimidating than the standard Arch Linux installer.

I hope this helps clarify things a bit. If you have any more questions, let me know!
